### ISSUE TITLE
Support OCaml 4.08 and 4.09

### ISSUE THREAD

**Issue by XVilka** [rlepigre/ocaml-earley#2]
There are many useful changes in [OCaml 4.08](https://discuss.ocaml.org/t/ocaml-4-08-1-released/4212) and [OCaml 4.09](https://discuss.ocaml.org/t/ocaml-4-09-0-released/4384/2).

**Comment by rlepigre** [comment]
Sure, we are aware of this. We will add support whenever possible (but are quite busy at the moment).

**Comment by Rehan-MALAK** [comment]
Is there a quick hack for this ?

**Comment by rlepigre** [comment]
No there is no quick hack unfortunately, but I am working on this. The main problem is that pretty much every version of the OCaml language has a different interface to the AST, and we need to be able to support a bunch of versions at once. This means that we need our own wrapper library on top of (part of) the compiler libs, and for now the current interface is not general enough for 4.08 and 4.09 due to some recent (rather extensive) changes to the AST. I'm working on this though, so we'll probably have a working version in a couple of months. (I don't have much time to work on that currently).

**Comment by vbgl** [comment]
This remark is probably naive, but isn’t the [ocaml-migrate-parsetree library](https://github.com/ocaml-ppx/ocaml-migrate-parsetree) supposed to address the issue of the evolving AST?

**Comment by XVilka** [comment]
@vbgl yes, but also there are efforts to improve it (along with the ppx ecosystem): https://discuss.ocaml.org/t/the-future-of-ppx/3766

**Comment by rlepigre** [comment]
> This remark is probably naive, but isn’t the [ocaml-migrate-parsetree library](https://github.com/ocaml-ppx/ocaml-migrate-parsetree) supposed to address the issue of the evolving AST?

Yeah, perhaps that could work. I have not looked into that seriously enough yet. Maybe I should since it would definitely be easier to only support a fixed OCaml AST and then do the necessary translation for the other versions.

**Comment by rlepigre** [comment]
All versions for 4.7.0 are now supported, and this should remain robust to newer versions.
